# Generated by Django 4.2.4 on 2023-08-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flower',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
