# Generated by Django 4.2.4 on 2023-08-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_flower_price_alter_flower_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='category',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='flower',
            name='color',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='flower',
            name='picture',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flower',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='flower',
            name='scientific_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
