# Generated by Django 4.2.4 on 2023-08-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_flower_category_flower_color_flower_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='picture',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
