# Generated by Django 4.2.4 on 2023-08-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_flower_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='flower',
            name='color',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='flower',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='flower',
            name='scientific_name',
            field=models.CharField(max_length=200),
        ),
    ]
