# Generated by Django 4.2.4 on 2023-08-13 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_alter_flower_id_alter_orders_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='item_color',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='item_picture',
        ),
    ]
