# Generated by Django 4.2.4 on 2023-08-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_remove_orders_item_color_remove_orders_item_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='picture',
            field=models.ImageField(upload_to='static/uploads/%Y/%m/%d/'),
        ),
    ]
