# Generated by Django 4.2.4 on 2023-09-05 06:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0017_alter_cart_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=200)),
                ("picture", models.ImageField(upload_to="static/uploads/%Y/%m/%d/")),
                ("added_date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name="flower",
            name="color",
        ),
        migrations.AlterField(
            model_name="flower",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mainApp.category"
            ),
        ),
    ]
